spring:
  application:
    name: "cards"
  datasource:
    username: root
    password: ''
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 9000
springdoc:
  swagger-ui:
    path: /swagger-ui.html