spring:
  application:
    name: "cards"
  datasource:
    username: root
    password: ''
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    import:
      - "application_prod.yml"
      - "application_qa.yml"

server:
  port: 9000

springdoc:
  swagger-ui:
    path: /swagger-ui.html

build:
  version: "3.0"

cards:
  message: "Welcome to MicroService Bank App ...local Card Api"
  contactDetails:
    name: Henry Taiwo - HT
    email: taiowh782@gmail.com
  onCallSupport:
    - +(234)8 159 602 684
